# Relay5
# Реле с одним каналом, светодиодом, кнопкой и выключателем

substitutions:
  friendly_unit_name: "Relay5"

packages:
  - !include sub/relay_with_led.yaml  # реле со светодиодом
  - !include sub/relay_button.yaml    # кнопка реле
  - !include sub/relay_switch.yaml    # выключатель реле
  - !include sub/relay_pos.yaml       # функция восстановления состояния реле
