# Relay4
# Реле с одним каналом, светодиодом и кнопкой

substitutions:
  friendly_unit_name: "Relay4"

packages:
  - !include sub/relay_with_led.yaml  # реле со светодиодом
  - !include sub/relay_button.yaml    # кнопка реле
  - !include sub/relay_pos.yaml       # функция восстановления состояния реле
